[build]
  base = "pharmacy-management"
  publish = "build"
  # Thêm CI=false vào trước câu lệnh build
  command = "CI=false npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://websatiudu-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200